# Generated by Django 5.2.7 on 2025-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('jurusan', models.CharField(blank=True, max_length=100, verbose_name='Jurusan')),
                ('angkatan', models.PositiveIntegerField(blank=True, null=True, verbose_name='Angkatan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
    ]
