# Generated by Django 5.2.7 on 2025-10-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
    ]
