# Generated by Django 5.2.8 on 2025-11-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, choices=[('artificial_intelligence_and_robotics', 'AIR'), ('business_mathematics', 'BM'), ('digital_business_technology', 'DBT'), ('product_design_engineering', 'PDE'), ('energy_business_technology', 'EBT'), ('food_business_tevchnology', 'FBT')], default='artificial_intelligence_and_robotics', max_length=100, null=True),
        ),
    ]
